// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqTpouO5h5ZoE1hjOyrWI3E2ezBrMSmAk',
    appId: '1:779499834281:web:9f71e8e33da74285de52b8',
    messagingSenderId: '779499834281',
    projectId: 'sneaks4sure-1088',
    authDomain: 'sneaks4sure-1088.firebaseapp.com',
    storageBucket: 'sneaks4sure-1088.appspot.com',
    measurementId: 'G-XGMSTYWJJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqLdvqgLBepbFIRFZ2lOt61GCvPhZVCyQ',
    appId: '1:779499834281:android:ab58de092e238c0cde52b8',
    messagingSenderId: '779499834281',
    projectId: 'sneaks4sure-1088',
    storageBucket: 'sneaks4sure-1088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Qn-XjyKgN5pXiD7ewjcwwBpSumQyLp4',
    appId: '1:779499834281:ios:e5786b816d4ba3e7de52b8',
    messagingSenderId: '779499834281',
    projectId: 'sneaks4sure-1088',
    storageBucket: 'sneaks4sure-1088.appspot.com',
    androidClientId: '779499834281-hsi8nkiig6lieblqlph9m114tkt8vb0g.apps.googleusercontent.com',
    iosClientId: '779499834281-567i05q44pddogjdsernf4hq8a8p4g37.apps.googleusercontent.com',
    iosBundleId: 'com.example.s4sMobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Qn-XjyKgN5pXiD7ewjcwwBpSumQyLp4',
    appId: '1:779499834281:ios:e5786b816d4ba3e7de52b8',
    messagingSenderId: '779499834281',
    projectId: 'sneaks4sure-1088',
    storageBucket: 'sneaks4sure-1088.appspot.com',
    androidClientId: '779499834281-hsi8nkiig6lieblqlph9m114tkt8vb0g.apps.googleusercontent.com',
    iosClientId: '779499834281-567i05q44pddogjdsernf4hq8a8p4g37.apps.googleusercontent.com',
    iosBundleId: 'com.example.s4sMobileapp',
  );
}
